# Generated by Django 6.0.4 on 2026-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course_interest', models.CharField(choices=[('web_development', 'Web Development'), ('data_science', 'Data Science'), ('ux_design', 'UX Design'), ('devops', 'DevOps'), ('product_management', 'Product Management')], max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interviewing', 'Interviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
